//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COES.MVC.Extranet.UserServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/COES.Aplicacion.General.DTO")]
    [System.SerializableAttribute()]
    public partial class UserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> AREACODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AREALABORALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMPRESASField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LASTDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LASTUSERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOTIVOCONTACTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERCARGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> USERCHECKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short USERCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> USERCONNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERCORREOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> USERFACTIVACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> USERFBAJAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> USERFCREACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERLOGINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> USERMAXCONNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERPASSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERSTATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USERTLFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> USERVALIDATEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> AREACODE {
            get {
                return this.AREACODEField;
            }
            set {
                if ((this.AREACODEField.Equals(value) != true)) {
                    this.AREACODEField = value;
                    this.RaisePropertyChanged("AREACODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AREALABORAL {
            get {
                return this.AREALABORALField;
            }
            set {
                if ((object.ReferenceEquals(this.AREALABORALField, value) != true)) {
                    this.AREALABORALField = value;
                    this.RaisePropertyChanged("AREALABORAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMPRESAS {
            get {
                return this.EMPRESASField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPRESASField, value) != true)) {
                    this.EMPRESASField = value;
                    this.RaisePropertyChanged("EMPRESAS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LASTDATE {
            get {
                return this.LASTDATEField;
            }
            set {
                if ((this.LASTDATEField.Equals(value) != true)) {
                    this.LASTDATEField = value;
                    this.RaisePropertyChanged("LASTDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LASTUSER {
            get {
                return this.LASTUSERField;
            }
            set {
                if ((object.ReferenceEquals(this.LASTUSERField, value) != true)) {
                    this.LASTUSERField = value;
                    this.RaisePropertyChanged("LASTUSER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOTIVOCONTACTO {
            get {
                return this.MOTIVOCONTACTOField;
            }
            set {
                if ((object.ReferenceEquals(this.MOTIVOCONTACTOField, value) != true)) {
                    this.MOTIVOCONTACTOField = value;
                    this.RaisePropertyChanged("MOTIVOCONTACTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERCARGO {
            get {
                return this.USERCARGOField;
            }
            set {
                if ((object.ReferenceEquals(this.USERCARGOField, value) != true)) {
                    this.USERCARGOField = value;
                    this.RaisePropertyChanged("USERCARGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> USERCHECK {
            get {
                return this.USERCHECKField;
            }
            set {
                if ((this.USERCHECKField.Equals(value) != true)) {
                    this.USERCHECKField = value;
                    this.RaisePropertyChanged("USERCHECK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short USERCODE {
            get {
                return this.USERCODEField;
            }
            set {
                if ((this.USERCODEField.Equals(value) != true)) {
                    this.USERCODEField = value;
                    this.RaisePropertyChanged("USERCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> USERCONN {
            get {
                return this.USERCONNField;
            }
            set {
                if ((this.USERCONNField.Equals(value) != true)) {
                    this.USERCONNField = value;
                    this.RaisePropertyChanged("USERCONN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERCORREO {
            get {
                return this.USERCORREOField;
            }
            set {
                if ((object.ReferenceEquals(this.USERCORREOField, value) != true)) {
                    this.USERCORREOField = value;
                    this.RaisePropertyChanged("USERCORREO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> USERFACTIVACION {
            get {
                return this.USERFACTIVACIONField;
            }
            set {
                if ((this.USERFACTIVACIONField.Equals(value) != true)) {
                    this.USERFACTIVACIONField = value;
                    this.RaisePropertyChanged("USERFACTIVACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> USERFBAJA {
            get {
                return this.USERFBAJAField;
            }
            set {
                if ((this.USERFBAJAField.Equals(value) != true)) {
                    this.USERFBAJAField = value;
                    this.RaisePropertyChanged("USERFBAJA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> USERFCREACION {
            get {
                return this.USERFCREACIONField;
            }
            set {
                if ((this.USERFCREACIONField.Equals(value) != true)) {
                    this.USERFCREACIONField = value;
                    this.RaisePropertyChanged("USERFCREACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERLOGIN {
            get {
                return this.USERLOGINField;
            }
            set {
                if ((object.ReferenceEquals(this.USERLOGINField, value) != true)) {
                    this.USERLOGINField = value;
                    this.RaisePropertyChanged("USERLOGIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> USERMAXCONN {
            get {
                return this.USERMAXCONNField;
            }
            set {
                if ((this.USERMAXCONNField.Equals(value) != true)) {
                    this.USERMAXCONNField = value;
                    this.RaisePropertyChanged("USERMAXCONN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERNAME {
            get {
                return this.USERNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.USERNAMEField, value) != true)) {
                    this.USERNAMEField = value;
                    this.RaisePropertyChanged("USERNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERPASS {
            get {
                return this.USERPASSField;
            }
            set {
                if ((object.ReferenceEquals(this.USERPASSField, value) != true)) {
                    this.USERPASSField = value;
                    this.RaisePropertyChanged("USERPASS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERSTATE {
            get {
                return this.USERSTATEField;
            }
            set {
                if ((object.ReferenceEquals(this.USERSTATEField, value) != true)) {
                    this.USERSTATEField = value;
                    this.RaisePropertyChanged("USERSTATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USERTLF {
            get {
                return this.USERTLFField;
            }
            set {
                if ((object.ReferenceEquals(this.USERTLFField, value) != true)) {
                    this.USERTLFField = value;
                    this.RaisePropertyChanged("USERTLF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> USERVALIDATE {
            get {
                return this.USERVALIDATEField;
            }
            set {
                if ((this.USERVALIDATEField.Equals(value) != true)) {
                    this.USERVALIDATEField = value;
                    this.RaisePropertyChanged("USERVALIDATE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.coes.org.pe", ConfigurationName="UserServicio.IUserServicio")]
    public interface IUserServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IUserServicio/ListarTodosUsuarios", ReplyAction="www.coes.org.pe/IUserServicio/ListarTodosUsuariosResponse")]
        COES.MVC.Extranet.UserServicio.UserDTO[] ListarTodosUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IUserServicio/ListarTodosUsuarios", ReplyAction="www.coes.org.pe/IUserServicio/ListarTodosUsuariosResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.UserServicio.UserDTO[]> ListarTodosUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IUserServicio/ListarUsuariosxArea", ReplyAction="www.coes.org.pe/IUserServicio/ListarUsuariosxAreaResponse")]
        COES.MVC.Extranet.UserServicio.UserDTO[] ListarUsuariosxArea(short iAreaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IUserServicio/ListarUsuariosxArea", ReplyAction="www.coes.org.pe/IUserServicio/ListarUsuariosxAreaResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.UserServicio.UserDTO[]> ListarUsuariosxAreaAsync(short iAreaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IUserServicio/ListarUsuariosxCompania", ReplyAction="www.coes.org.pe/IUserServicio/ListarUsuariosxCompaniaResponse")]
        COES.MVC.Extranet.UserServicio.UserDTO[] ListarUsuariosxCompania(string sCompaniaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IUserServicio/ListarUsuariosxCompania", ReplyAction="www.coes.org.pe/IUserServicio/ListarUsuariosxCompaniaResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.UserServicio.UserDTO[]> ListarUsuariosxCompaniaAsync(string sCompaniaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IUserServicio/ListarUsuariosxNombre", ReplyAction="www.coes.org.pe/IUserServicio/ListarUsuariosxNombreResponse")]
        COES.MVC.Extranet.UserServicio.ListarUsuariosxNombreResponse ListarUsuariosxNombre(COES.MVC.Extranet.UserServicio.ListarUsuariosxNombreRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IUserServicio/ListarUsuariosxNombre", ReplyAction="www.coes.org.pe/IUserServicio/ListarUsuariosxNombreResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.UserServicio.ListarUsuariosxNombreResponse> ListarUsuariosxNombreAsync(COES.MVC.Extranet.UserServicio.ListarUsuariosxNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IUserServicio/TraerUsuario", ReplyAction="www.coes.org.pe/IUserServicio/TraerUsuarioResponse")]
        COES.MVC.Extranet.UserServicio.UserDTO TraerUsuario(short iUsuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IUserServicio/TraerUsuario", ReplyAction="www.coes.org.pe/IUserServicio/TraerUsuarioResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.UserServicio.UserDTO> TraerUsuarioAsync(short iUsuarioId);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IUserServicio/TraerUsuarioxLogin", ReplyAction="www.coes.org.pe/IUserServicio/TraerUsuarioxLoginResponse")]
        COES.MVC.Extranet.UserServicio.UserDTO TraerUsuarioxLogin(string sLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IUserServicio/TraerUsuarioxLogin", ReplyAction="www.coes.org.pe/IUserServicio/TraerUsuarioxLoginResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.UserServicio.UserDTO> TraerUsuarioxLoginAsync(string sLogin);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarUsuariosxNombre", WrapperNamespace="www.coes.org.pe", IsWrapped=true)]
    public partial class ListarUsuariosxNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.org.pe", Order=0)]
        public int indicePagina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.org.pe", Order=1)]
        public string coincidencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.org.pe", Order=2)]
        public int totalPaginas;
        
        public ListarUsuariosxNombreRequest() {
        }
        
        public ListarUsuariosxNombreRequest(int indicePagina, string coincidencia, int totalPaginas) {
            this.indicePagina = indicePagina;
            this.coincidencia = coincidencia;
            this.totalPaginas = totalPaginas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarUsuariosxNombreResponse", WrapperNamespace="www.coes.org.pe", IsWrapped=true)]
    public partial class ListarUsuariosxNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.org.pe", Order=0)]
        public COES.MVC.Extranet.UserServicio.UserDTO[] ListarUsuariosxNombreResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.org.pe", Order=1)]
        public int totalPaginas;
        
        public ListarUsuariosxNombreResponse() {
        }
        
        public ListarUsuariosxNombreResponse(COES.MVC.Extranet.UserServicio.UserDTO[] ListarUsuariosxNombreResult, int totalPaginas) {
            this.ListarUsuariosxNombreResult = ListarUsuariosxNombreResult;
            this.totalPaginas = totalPaginas;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServicioChannel : COES.MVC.Extranet.UserServicio.IUserServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServicioClient : System.ServiceModel.ClientBase<COES.MVC.Extranet.UserServicio.IUserServicio>, COES.MVC.Extranet.UserServicio.IUserServicio {
        
        public UserServicioClient() {
        }
        
        public UserServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public COES.MVC.Extranet.UserServicio.UserDTO[] ListarTodosUsuarios() {
            return base.Channel.ListarTodosUsuarios();
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.UserServicio.UserDTO[]> ListarTodosUsuariosAsync() {
            return base.Channel.ListarTodosUsuariosAsync();
        }
        
        public COES.MVC.Extranet.UserServicio.UserDTO[] ListarUsuariosxArea(short iAreaId) {
            return base.Channel.ListarUsuariosxArea(iAreaId);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.UserServicio.UserDTO[]> ListarUsuariosxAreaAsync(short iAreaId) {
            return base.Channel.ListarUsuariosxAreaAsync(iAreaId);
        }
        
        public COES.MVC.Extranet.UserServicio.UserDTO[] ListarUsuariosxCompania(string sCompaniaId) {
            return base.Channel.ListarUsuariosxCompania(sCompaniaId);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.UserServicio.UserDTO[]> ListarUsuariosxCompaniaAsync(string sCompaniaId) {
            return base.Channel.ListarUsuariosxCompaniaAsync(sCompaniaId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.UserServicio.ListarUsuariosxNombreResponse COES.MVC.Extranet.UserServicio.IUserServicio.ListarUsuariosxNombre(COES.MVC.Extranet.UserServicio.ListarUsuariosxNombreRequest request) {
            return base.Channel.ListarUsuariosxNombre(request);
        }
        
        public COES.MVC.Extranet.UserServicio.UserDTO[] ListarUsuariosxNombre(int indicePagina, string coincidencia, ref int totalPaginas) {
            COES.MVC.Extranet.UserServicio.ListarUsuariosxNombreRequest inValue = new COES.MVC.Extranet.UserServicio.ListarUsuariosxNombreRequest();
            inValue.indicePagina = indicePagina;
            inValue.coincidencia = coincidencia;
            inValue.totalPaginas = totalPaginas;
            COES.MVC.Extranet.UserServicio.ListarUsuariosxNombreResponse retVal = ((COES.MVC.Extranet.UserServicio.IUserServicio)(this)).ListarUsuariosxNombre(inValue);
            totalPaginas = retVal.totalPaginas;
            return retVal.ListarUsuariosxNombreResult;
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.UserServicio.ListarUsuariosxNombreResponse> ListarUsuariosxNombreAsync(COES.MVC.Extranet.UserServicio.ListarUsuariosxNombreRequest request) {
            return base.Channel.ListarUsuariosxNombreAsync(request);
        }
        
        public COES.MVC.Extranet.UserServicio.UserDTO TraerUsuario(short iUsuarioId) {
            return base.Channel.TraerUsuario(iUsuarioId);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.UserServicio.UserDTO> TraerUsuarioAsync(short iUsuarioId) {
            return base.Channel.TraerUsuarioAsync(iUsuarioId);
        }
        
        public COES.MVC.Extranet.UserServicio.UserDTO TraerUsuarioxLogin(string sLogin) {
            return base.Channel.TraerUsuarioxLogin(sLogin);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.UserServicio.UserDTO> TraerUsuarioxLoginAsync(string sLogin) {
            return base.Channel.TraerUsuarioxLoginAsync(sLogin);
        }
    }
}
