//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COES.MVC.Extranet.srGestor {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srGestor.ICMSManager")]
    public interface ICMSManager {
        
        // CODEGEN: Parameter 'GetFileResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetFile", ReplyAction="http://tempuri.org/ICMSManager/GetFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COES.MVC.Extranet.srGestor.GetFileResponse GetFile(COES.MVC.Extranet.srGestor.GetFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetFile", ReplyAction="http://tempuri.org/ICMSManager/GetFileResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetFileResponse> GetFileAsync(COES.MVC.Extranet.srGestor.GetFileRequest request);
        
        // CODEGEN: Parameter 'GetFileWithContentAndNameResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetFileWithContentAndName", ReplyAction="http://tempuri.org/ICMSManager/GetFileWithContentAndNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COES.MVC.Extranet.srGestor.GetFileWithContentAndNameResponse GetFileWithContentAndName(COES.MVC.Extranet.srGestor.GetFileWithContentAndNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetFileWithContentAndName", ReplyAction="http://tempuri.org/ICMSManager/GetFileWithContentAndNameResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetFileWithContentAndNameResponse> GetFileWithContentAndNameAsync(COES.MVC.Extranet.srGestor.GetFileWithContentAndNameRequest request);
        
        // CODEGEN: Parameter 'GetSpacesByPathResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetSpacesByPath", ReplyAction="http://tempuri.org/ICMSManager/GetSpacesByPathResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COES.MVC.Extranet.srGestor.GetSpacesByPathResponse GetSpacesByPath(COES.MVC.Extranet.srGestor.GetSpacesByPathRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetSpacesByPath", ReplyAction="http://tempuri.org/ICMSManager/GetSpacesByPathResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetSpacesByPathResponse> GetSpacesByPathAsync(COES.MVC.Extranet.srGestor.GetSpacesByPathRequest request);
        
        // CODEGEN: Parameter 'GetFilesByPathResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetFilesByPath", ReplyAction="http://tempuri.org/ICMSManager/GetFilesByPathResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COES.MVC.Extranet.srGestor.GetFilesByPathResponse GetFilesByPath(COES.MVC.Extranet.srGestor.GetFilesByPathRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetFilesByPath", ReplyAction="http://tempuri.org/ICMSManager/GetFilesByPathResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetFilesByPathResponse> GetFilesByPathAsync(COES.MVC.Extranet.srGestor.GetFilesByPathRequest request);
        
        // CODEGEN: Parameter 'GetSpacesByUUIDResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetSpacesByUUID", ReplyAction="http://tempuri.org/ICMSManager/GetSpacesByUUIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COES.MVC.Extranet.srGestor.GetSpacesByUUIDResponse GetSpacesByUUID(COES.MVC.Extranet.srGestor.GetSpacesByUUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetSpacesByUUID", ReplyAction="http://tempuri.org/ICMSManager/GetSpacesByUUIDResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetSpacesByUUIDResponse> GetSpacesByUUIDAsync(COES.MVC.Extranet.srGestor.GetSpacesByUUIDRequest request);
        
        // CODEGEN: Parameter 'GetFilesByUUIDResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetFilesByUUID", ReplyAction="http://tempuri.org/ICMSManager/GetFilesByUUIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COES.MVC.Extranet.srGestor.GetFilesByUUIDResponse GetFilesByUUID(COES.MVC.Extranet.srGestor.GetFilesByUUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetFilesByUUID", ReplyAction="http://tempuri.org/ICMSManager/GetFilesByUUIDResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetFilesByUUIDResponse> GetFilesByUUIDAsync(COES.MVC.Extranet.srGestor.GetFilesByUUIDRequest request);
        
        // CODEGEN: Parameter 'GetPathByUUIDResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetPathByUUID", ReplyAction="http://tempuri.org/ICMSManager/GetPathByUUIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COES.MVC.Extranet.srGestor.GetPathByUUIDResponse GetPathByUUID(COES.MVC.Extranet.srGestor.GetPathByUUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetPathByUUID", ReplyAction="http://tempuri.org/ICMSManager/GetPathByUUIDResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetPathByUUIDResponse> GetPathByUUIDAsync(COES.MVC.Extranet.srGestor.GetPathByUUIDRequest request);
        
        // CODEGEN: Parameter 'GetPathByPathResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetPathByPath", ReplyAction="http://tempuri.org/ICMSManager/GetPathByPathResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COES.MVC.Extranet.srGestor.GetPathByPathResponse GetPathByPath(COES.MVC.Extranet.srGestor.GetPathByPathRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetPathByPath", ReplyAction="http://tempuri.org/ICMSManager/GetPathByPathResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetPathByPathResponse> GetPathByPathAsync(COES.MVC.Extranet.srGestor.GetPathByPathRequest request);
        
        // CODEGEN: Parameter 'GetDataByUUIDResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetDataByUUID", ReplyAction="http://tempuri.org/ICMSManager/GetDataByUUIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COES.MVC.Extranet.srGestor.GetDataByUUIDResponse GetDataByUUID(COES.MVC.Extranet.srGestor.GetDataByUUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetDataByUUID", ReplyAction="http://tempuri.org/ICMSManager/GetDataByUUIDResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetDataByUUIDResponse> GetDataByUUIDAsync(COES.MVC.Extranet.srGestor.GetDataByUUIDRequest request);
        
        // CODEGEN: Parameter 'GetDataByPathResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetDataByPath", ReplyAction="http://tempuri.org/ICMSManager/GetDataByPathResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COES.MVC.Extranet.srGestor.GetDataByPathResponse GetDataByPath(COES.MVC.Extranet.srGestor.GetDataByPathRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetDataByPath", ReplyAction="http://tempuri.org/ICMSManager/GetDataByPathResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetDataByPathResponse> GetDataByPathAsync(COES.MVC.Extranet.srGestor.GetDataByPathRequest request);
        
        // CODEGEN: Parameter 'GetDataByPathWithTypeResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetDataByPathWithType", ReplyAction="http://tempuri.org/ICMSManager/GetDataByPathWithTypeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COES.MVC.Extranet.srGestor.GetDataByPathWithTypeResponse GetDataByPathWithType(COES.MVC.Extranet.srGestor.GetDataByPathWithTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetDataByPathWithType", ReplyAction="http://tempuri.org/ICMSManager/GetDataByPathWithTypeResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetDataByPathWithTypeResponse> GetDataByPathWithTypeAsync(COES.MVC.Extranet.srGestor.GetDataByPathWithTypeRequest request);
        
        // CODEGEN: Parameter 'GetDataWithMetadataByPathResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetDataWithMetadataByPath", ReplyAction="http://tempuri.org/ICMSManager/GetDataWithMetadataByPathResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COES.MVC.Extranet.srGestor.GetDataWithMetadataByPathResponse GetDataWithMetadataByPath(COES.MVC.Extranet.srGestor.GetDataWithMetadataByPathRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetDataWithMetadataByPath", ReplyAction="http://tempuri.org/ICMSManager/GetDataWithMetadataByPathResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetDataWithMetadataByPathResponse> GetDataWithMetadataByPathAsync(COES.MVC.Extranet.srGestor.GetDataWithMetadataByPathRequest request);
        
        // CODEGEN: Parameter 'GetDataAsJsonResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetDataAsJson", ReplyAction="http://tempuri.org/ICMSManager/GetDataAsJsonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COES.MVC.Extranet.srGestor.GetDataAsJsonResponse GetDataAsJson(COES.MVC.Extranet.srGestor.GetDataAsJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetDataAsJson", ReplyAction="http://tempuri.org/ICMSManager/GetDataAsJsonResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetDataAsJsonResponse> GetDataAsJsonAsync(COES.MVC.Extranet.srGestor.GetDataAsJsonRequest request);
        
        // CODEGEN: Parameter 'luceneQuery' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetTotalNodes", ReplyAction="http://tempuri.org/ICMSManager/GetTotalNodesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COES.MVC.Extranet.srGestor.GetTotalNodesResponse GetTotalNodes(COES.MVC.Extranet.srGestor.GetTotalNodesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetTotalNodes", ReplyAction="http://tempuri.org/ICMSManager/GetTotalNodesResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetTotalNodesResponse> GetTotalNodesAsync(COES.MVC.Extranet.srGestor.GetTotalNodesRequest request);
        
        // CODEGEN: Parameter 'path' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetTotalNodesWithType", ReplyAction="http://tempuri.org/ICMSManager/GetTotalNodesWithTypeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COES.MVC.Extranet.srGestor.GetTotalNodesWithTypeResponse GetTotalNodesWithType(COES.MVC.Extranet.srGestor.GetTotalNodesWithTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetTotalNodesWithType", ReplyAction="http://tempuri.org/ICMSManager/GetTotalNodesWithTypeResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetTotalNodesWithTypeResponse> GetTotalNodesWithTypeAsync(COES.MVC.Extranet.srGestor.GetTotalNodesWithTypeRequest request);
        
        // CODEGEN: Parameter 'GetNormasLegalesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetNormasLegales", ReplyAction="http://tempuri.org/ICMSManager/GetNormasLegalesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COES.MVC.Extranet.srGestor.GetNormasLegalesResponse GetNormasLegales(COES.MVC.Extranet.srGestor.GetNormasLegalesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetNormasLegales", ReplyAction="http://tempuri.org/ICMSManager/GetNormasLegalesResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetNormasLegalesResponse> GetNormasLegalesAsync(COES.MVC.Extranet.srGestor.GetNormasLegalesRequest request);
        
        // CODEGEN: Parameter 'GetFileIdByNameResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetFileIdByName", ReplyAction="http://tempuri.org/ICMSManager/GetFileIdByNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        COES.MVC.Extranet.srGestor.GetFileIdByNameResponse GetFileIdByName(COES.MVC.Extranet.srGestor.GetFileIdByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICMSManager/GetFileIdByName", ReplyAction="http://tempuri.org/ICMSManager/GetFileIdByNameResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetFileIdByNameResponse> GetFileIdByNameAsync(COES.MVC.Extranet.srGestor.GetFileIdByNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id;
        
        public GetFileRequest() {
        }
        
        public GetFileRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] GetFileResult;
        
        public GetFileResponse() {
        }
        
        public GetFileResponse(byte[] GetFileResult) {
            this.GetFileResult = GetFileResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/wsGC")]
    public partial class File : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentTypeField;
        
        private byte[] dataAsStreamByteField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
                this.RaisePropertyChanged("ContentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=1)]
        public byte[] DataAsStreamByte {
            get {
                return this.dataAsStreamByteField;
            }
            set {
                this.dataAsStreamByteField = value;
                this.RaisePropertyChanged("DataAsStreamByte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/wsGC")]
    public partial class Espacio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string asuntoField;
        
        private string dispositivoLegalField;
        
        private string entidadField;
        
        private string fechaPublicacionField;
        
        private string idField;
        
        private string nombreField;
        
        private string pathField;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Asunto {
            get {
                return this.asuntoField;
            }
            set {
                this.asuntoField = value;
                this.RaisePropertyChanged("Asunto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string DispositivoLegal {
            get {
                return this.dispositivoLegalField;
            }
            set {
                this.dispositivoLegalField = value;
                this.RaisePropertyChanged("DispositivoLegal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Entidad {
            get {
                return this.entidadField;
            }
            set {
                this.entidadField = value;
                this.RaisePropertyChanged("Entidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string FechaPublicacion {
            get {
                return this.fechaPublicacionField;
            }
            set {
                this.fechaPublicacionField = value;
                this.RaisePropertyChanged("FechaPublicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
                this.RaisePropertyChanged("Path");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("Titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileWithContentAndName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileWithContentAndNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id;
        
        public GetFileWithContentAndNameRequest() {
        }
        
        public GetFileWithContentAndNameRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileWithContentAndNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileWithContentAndNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public COES.MVC.Extranet.srGestor.File GetFileWithContentAndNameResult;
        
        public GetFileWithContentAndNameResponse() {
        }
        
        public GetFileWithContentAndNameResponse(COES.MVC.Extranet.srGestor.File GetFileWithContentAndNameResult) {
            this.GetFileWithContentAndNameResult = GetFileWithContentAndNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSpacesByPath", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSpacesByPathRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string path;
        
        public GetSpacesByPathRequest() {
        }
        
        public GetSpacesByPathRequest(string path) {
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSpacesByPathResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSpacesByPathResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetSpacesByPathResult;
        
        public GetSpacesByPathResponse() {
        }
        
        public GetSpacesByPathResponse(System.Data.DataTable GetSpacesByPathResult) {
            this.GetSpacesByPathResult = GetSpacesByPathResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilesByPath", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFilesByPathRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string path;
        
        public GetFilesByPathRequest() {
        }
        
        public GetFilesByPathRequest(string path) {
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilesByPathResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFilesByPathResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetFilesByPathResult;
        
        public GetFilesByPathResponse() {
        }
        
        public GetFilesByPathResponse(System.Data.DataTable GetFilesByPathResult) {
            this.GetFilesByPathResult = GetFilesByPathResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSpacesByUUID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSpacesByUUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id;
        
        public GetSpacesByUUIDRequest() {
        }
        
        public GetSpacesByUUIDRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSpacesByUUIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSpacesByUUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetSpacesByUUIDResult;
        
        public GetSpacesByUUIDResponse() {
        }
        
        public GetSpacesByUUIDResponse(System.Data.DataTable GetSpacesByUUIDResult) {
            this.GetSpacesByUUIDResult = GetSpacesByUUIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilesByUUID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFilesByUUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id;
        
        public GetFilesByUUIDRequest() {
        }
        
        public GetFilesByUUIDRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilesByUUIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFilesByUUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetFilesByUUIDResult;
        
        public GetFilesByUUIDResponse() {
        }
        
        public GetFilesByUUIDResponse(System.Data.DataTable GetFilesByUUIDResult) {
            this.GetFilesByUUIDResult = GetFilesByUUIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPathByUUID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPathByUUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id;
        
        public GetPathByUUIDRequest() {
        }
        
        public GetPathByUUIDRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPathByUUIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPathByUUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetPathByUUIDResult;
        
        public GetPathByUUIDResponse() {
        }
        
        public GetPathByUUIDResponse(System.Data.DataTable GetPathByUUIDResult) {
            this.GetPathByUUIDResult = GetPathByUUIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPathByPath", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPathByPathRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string path;
        
        public GetPathByPathRequest() {
        }
        
        public GetPathByPathRequest(string path) {
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPathByPathResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPathByPathResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetPathByPathResult;
        
        public GetPathByPathResponse() {
        }
        
        public GetPathByPathResponse(System.Data.DataTable GetPathByPathResult) {
            this.GetPathByPathResult = GetPathByPathResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataByUUID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataByUUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id;
        
        public GetDataByUUIDRequest() {
        }
        
        public GetDataByUUIDRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataByUUIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataByUUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetDataByUUIDResult;
        
        public GetDataByUUIDResponse() {
        }
        
        public GetDataByUUIDResponse(System.Data.DataTable GetDataByUUIDResult) {
            this.GetDataByUUIDResult = GetDataByUUIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataByPath", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataByPathRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id;
        
        public GetDataByPathRequest() {
        }
        
        public GetDataByPathRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataByPathResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataByPathResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetDataByPathResult;
        
        public GetDataByPathResponse() {
        }
        
        public GetDataByPathResponse(System.Data.DataTable GetDataByPathResult) {
            this.GetDataByPathResult = GetDataByPathResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataByPathWithType", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataByPathWithTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string path;
        
        public GetDataByPathWithTypeRequest() {
        }
        
        public GetDataByPathWithTypeRequest(string path) {
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataByPathWithTypeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataByPathWithTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetDataByPathWithTypeResult;
        
        public GetDataByPathWithTypeResponse() {
        }
        
        public GetDataByPathWithTypeResponse(System.Data.DataTable GetDataByPathWithTypeResult) {
            this.GetDataByPathWithTypeResult = GetDataByPathWithTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataWithMetadataByPath", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataWithMetadataByPathRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string typeMetadata;
        
        public GetDataWithMetadataByPathRequest() {
        }
        
        public GetDataWithMetadataByPathRequest(string path, string typeMetadata) {
            this.path = path;
            this.typeMetadata = typeMetadata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataWithMetadataByPathResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataWithMetadataByPathResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetDataWithMetadataByPathResult;
        
        public GetDataWithMetadataByPathResponse() {
        }
        
        public GetDataWithMetadataByPathResponse(System.Data.DataTable GetDataWithMetadataByPathResult) {
            this.GetDataWithMetadataByPathResult = GetDataWithMetadataByPathResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataAsJson", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataAsJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string luceneQuery;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int start;
        
        public GetDataAsJsonRequest() {
        }
        
        public GetDataAsJsonRequest(string luceneQuery, int pageSize, int start) {
            this.luceneQuery = luceneQuery;
            this.pageSize = pageSize;
            this.start = start;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataAsJsonResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataAsJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/wsGC")]
        public COES.MVC.Extranet.srGestor.Espacio[] GetDataAsJsonResult;
        
        public GetDataAsJsonResponse() {
        }
        
        public GetDataAsJsonResponse(COES.MVC.Extranet.srGestor.Espacio[] GetDataAsJsonResult) {
            this.GetDataAsJsonResult = GetDataAsJsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTotalNodes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTotalNodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string luceneQuery;
        
        public GetTotalNodesRequest() {
        }
        
        public GetTotalNodesRequest(string luceneQuery) {
            this.luceneQuery = luceneQuery;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTotalNodesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTotalNodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetTotalNodesResult;
        
        public GetTotalNodesResponse() {
        }
        
        public GetTotalNodesResponse(int GetTotalNodesResult) {
            this.GetTotalNodesResult = GetTotalNodesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTotalNodesWithType", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTotalNodesWithTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type;
        
        public GetTotalNodesWithTypeRequest() {
        }
        
        public GetTotalNodesWithTypeRequest(string path, string type) {
            this.path = path;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTotalNodesWithTypeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTotalNodesWithTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetTotalNodesWithTypeResult;
        
        public GetTotalNodesWithTypeResponse() {
        }
        
        public GetTotalNodesWithTypeResponse(int GetTotalNodesWithTypeResult) {
            this.GetTotalNodesWithTypeResult = GetTotalNodesWithTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNormasLegales", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetNormasLegalesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string type;
        
        public GetNormasLegalesRequest() {
        }
        
        public GetNormasLegalesRequest(string path, string type) {
            this.path = path;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNormasLegalesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetNormasLegalesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable GetNormasLegalesResult;
        
        public GetNormasLegalesResponse() {
        }
        
        public GetNormasLegalesResponse(System.Data.DataTable GetNormasLegalesResult) {
            this.GetNormasLegalesResult = GetNormasLegalesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileIdByName", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileIdByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name;
        
        public GetFileIdByNameRequest() {
        }
        
        public GetFileIdByNameRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileIdByNameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileIdByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetFileIdByNameResult;
        
        public GetFileIdByNameResponse() {
        }
        
        public GetFileIdByNameResponse(string GetFileIdByNameResult) {
            this.GetFileIdByNameResult = GetFileIdByNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICMSManagerChannel : COES.MVC.Extranet.srGestor.ICMSManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CMSManagerClient : System.ServiceModel.ClientBase<COES.MVC.Extranet.srGestor.ICMSManager>, COES.MVC.Extranet.srGestor.ICMSManager {
        
        public CMSManagerClient() {
        }
        
        public CMSManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CMSManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CMSManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CMSManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.srGestor.GetFileResponse COES.MVC.Extranet.srGestor.ICMSManager.GetFile(COES.MVC.Extranet.srGestor.GetFileRequest request) {
            return base.Channel.GetFile(request);
        }
        
        public byte[] GetFile(string id) {
            COES.MVC.Extranet.srGestor.GetFileRequest inValue = new COES.MVC.Extranet.srGestor.GetFileRequest();
            inValue.id = id;
            COES.MVC.Extranet.srGestor.GetFileResponse retVal = ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetFile(inValue);
            return retVal.GetFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetFileResponse> COES.MVC.Extranet.srGestor.ICMSManager.GetFileAsync(COES.MVC.Extranet.srGestor.GetFileRequest request) {
            return base.Channel.GetFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetFileResponse> GetFileAsync(string id) {
            COES.MVC.Extranet.srGestor.GetFileRequest inValue = new COES.MVC.Extranet.srGestor.GetFileRequest();
            inValue.id = id;
            return ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.srGestor.GetFileWithContentAndNameResponse COES.MVC.Extranet.srGestor.ICMSManager.GetFileWithContentAndName(COES.MVC.Extranet.srGestor.GetFileWithContentAndNameRequest request) {
            return base.Channel.GetFileWithContentAndName(request);
        }
        
        public COES.MVC.Extranet.srGestor.File GetFileWithContentAndName(string id) {
            COES.MVC.Extranet.srGestor.GetFileWithContentAndNameRequest inValue = new COES.MVC.Extranet.srGestor.GetFileWithContentAndNameRequest();
            inValue.id = id;
            COES.MVC.Extranet.srGestor.GetFileWithContentAndNameResponse retVal = ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetFileWithContentAndName(inValue);
            return retVal.GetFileWithContentAndNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetFileWithContentAndNameResponse> COES.MVC.Extranet.srGestor.ICMSManager.GetFileWithContentAndNameAsync(COES.MVC.Extranet.srGestor.GetFileWithContentAndNameRequest request) {
            return base.Channel.GetFileWithContentAndNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetFileWithContentAndNameResponse> GetFileWithContentAndNameAsync(string id) {
            COES.MVC.Extranet.srGestor.GetFileWithContentAndNameRequest inValue = new COES.MVC.Extranet.srGestor.GetFileWithContentAndNameRequest();
            inValue.id = id;
            return ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetFileWithContentAndNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.srGestor.GetSpacesByPathResponse COES.MVC.Extranet.srGestor.ICMSManager.GetSpacesByPath(COES.MVC.Extranet.srGestor.GetSpacesByPathRequest request) {
            return base.Channel.GetSpacesByPath(request);
        }
        
        public System.Data.DataTable GetSpacesByPath(string path) {
            COES.MVC.Extranet.srGestor.GetSpacesByPathRequest inValue = new COES.MVC.Extranet.srGestor.GetSpacesByPathRequest();
            inValue.path = path;
            COES.MVC.Extranet.srGestor.GetSpacesByPathResponse retVal = ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetSpacesByPath(inValue);
            return retVal.GetSpacesByPathResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetSpacesByPathResponse> COES.MVC.Extranet.srGestor.ICMSManager.GetSpacesByPathAsync(COES.MVC.Extranet.srGestor.GetSpacesByPathRequest request) {
            return base.Channel.GetSpacesByPathAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetSpacesByPathResponse> GetSpacesByPathAsync(string path) {
            COES.MVC.Extranet.srGestor.GetSpacesByPathRequest inValue = new COES.MVC.Extranet.srGestor.GetSpacesByPathRequest();
            inValue.path = path;
            return ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetSpacesByPathAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.srGestor.GetFilesByPathResponse COES.MVC.Extranet.srGestor.ICMSManager.GetFilesByPath(COES.MVC.Extranet.srGestor.GetFilesByPathRequest request) {
            return base.Channel.GetFilesByPath(request);
        }
        
        public System.Data.DataTable GetFilesByPath(string path) {
            COES.MVC.Extranet.srGestor.GetFilesByPathRequest inValue = new COES.MVC.Extranet.srGestor.GetFilesByPathRequest();
            inValue.path = path;
            COES.MVC.Extranet.srGestor.GetFilesByPathResponse retVal = ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetFilesByPath(inValue);
            return retVal.GetFilesByPathResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetFilesByPathResponse> COES.MVC.Extranet.srGestor.ICMSManager.GetFilesByPathAsync(COES.MVC.Extranet.srGestor.GetFilesByPathRequest request) {
            return base.Channel.GetFilesByPathAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetFilesByPathResponse> GetFilesByPathAsync(string path) {
            COES.MVC.Extranet.srGestor.GetFilesByPathRequest inValue = new COES.MVC.Extranet.srGestor.GetFilesByPathRequest();
            inValue.path = path;
            return ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetFilesByPathAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.srGestor.GetSpacesByUUIDResponse COES.MVC.Extranet.srGestor.ICMSManager.GetSpacesByUUID(COES.MVC.Extranet.srGestor.GetSpacesByUUIDRequest request) {
            return base.Channel.GetSpacesByUUID(request);
        }
        
        public System.Data.DataTable GetSpacesByUUID(string id) {
            COES.MVC.Extranet.srGestor.GetSpacesByUUIDRequest inValue = new COES.MVC.Extranet.srGestor.GetSpacesByUUIDRequest();
            inValue.id = id;
            COES.MVC.Extranet.srGestor.GetSpacesByUUIDResponse retVal = ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetSpacesByUUID(inValue);
            return retVal.GetSpacesByUUIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetSpacesByUUIDResponse> COES.MVC.Extranet.srGestor.ICMSManager.GetSpacesByUUIDAsync(COES.MVC.Extranet.srGestor.GetSpacesByUUIDRequest request) {
            return base.Channel.GetSpacesByUUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetSpacesByUUIDResponse> GetSpacesByUUIDAsync(string id) {
            COES.MVC.Extranet.srGestor.GetSpacesByUUIDRequest inValue = new COES.MVC.Extranet.srGestor.GetSpacesByUUIDRequest();
            inValue.id = id;
            return ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetSpacesByUUIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.srGestor.GetFilesByUUIDResponse COES.MVC.Extranet.srGestor.ICMSManager.GetFilesByUUID(COES.MVC.Extranet.srGestor.GetFilesByUUIDRequest request) {
            return base.Channel.GetFilesByUUID(request);
        }
        
        public System.Data.DataTable GetFilesByUUID(string id) {
            COES.MVC.Extranet.srGestor.GetFilesByUUIDRequest inValue = new COES.MVC.Extranet.srGestor.GetFilesByUUIDRequest();
            inValue.id = id;
            COES.MVC.Extranet.srGestor.GetFilesByUUIDResponse retVal = ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetFilesByUUID(inValue);
            return retVal.GetFilesByUUIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetFilesByUUIDResponse> COES.MVC.Extranet.srGestor.ICMSManager.GetFilesByUUIDAsync(COES.MVC.Extranet.srGestor.GetFilesByUUIDRequest request) {
            return base.Channel.GetFilesByUUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetFilesByUUIDResponse> GetFilesByUUIDAsync(string id) {
            COES.MVC.Extranet.srGestor.GetFilesByUUIDRequest inValue = new COES.MVC.Extranet.srGestor.GetFilesByUUIDRequest();
            inValue.id = id;
            return ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetFilesByUUIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.srGestor.GetPathByUUIDResponse COES.MVC.Extranet.srGestor.ICMSManager.GetPathByUUID(COES.MVC.Extranet.srGestor.GetPathByUUIDRequest request) {
            return base.Channel.GetPathByUUID(request);
        }
        
        public System.Data.DataTable GetPathByUUID(string id) {
            COES.MVC.Extranet.srGestor.GetPathByUUIDRequest inValue = new COES.MVC.Extranet.srGestor.GetPathByUUIDRequest();
            inValue.id = id;
            COES.MVC.Extranet.srGestor.GetPathByUUIDResponse retVal = ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetPathByUUID(inValue);
            return retVal.GetPathByUUIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetPathByUUIDResponse> COES.MVC.Extranet.srGestor.ICMSManager.GetPathByUUIDAsync(COES.MVC.Extranet.srGestor.GetPathByUUIDRequest request) {
            return base.Channel.GetPathByUUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetPathByUUIDResponse> GetPathByUUIDAsync(string id) {
            COES.MVC.Extranet.srGestor.GetPathByUUIDRequest inValue = new COES.MVC.Extranet.srGestor.GetPathByUUIDRequest();
            inValue.id = id;
            return ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetPathByUUIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.srGestor.GetPathByPathResponse COES.MVC.Extranet.srGestor.ICMSManager.GetPathByPath(COES.MVC.Extranet.srGestor.GetPathByPathRequest request) {
            return base.Channel.GetPathByPath(request);
        }
        
        public System.Data.DataTable GetPathByPath(string path) {
            COES.MVC.Extranet.srGestor.GetPathByPathRequest inValue = new COES.MVC.Extranet.srGestor.GetPathByPathRequest();
            inValue.path = path;
            COES.MVC.Extranet.srGestor.GetPathByPathResponse retVal = ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetPathByPath(inValue);
            return retVal.GetPathByPathResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetPathByPathResponse> COES.MVC.Extranet.srGestor.ICMSManager.GetPathByPathAsync(COES.MVC.Extranet.srGestor.GetPathByPathRequest request) {
            return base.Channel.GetPathByPathAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetPathByPathResponse> GetPathByPathAsync(string path) {
            COES.MVC.Extranet.srGestor.GetPathByPathRequest inValue = new COES.MVC.Extranet.srGestor.GetPathByPathRequest();
            inValue.path = path;
            return ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetPathByPathAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.srGestor.GetDataByUUIDResponse COES.MVC.Extranet.srGestor.ICMSManager.GetDataByUUID(COES.MVC.Extranet.srGestor.GetDataByUUIDRequest request) {
            return base.Channel.GetDataByUUID(request);
        }
        
        public System.Data.DataTable GetDataByUUID(string id) {
            COES.MVC.Extranet.srGestor.GetDataByUUIDRequest inValue = new COES.MVC.Extranet.srGestor.GetDataByUUIDRequest();
            inValue.id = id;
            COES.MVC.Extranet.srGestor.GetDataByUUIDResponse retVal = ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetDataByUUID(inValue);
            return retVal.GetDataByUUIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetDataByUUIDResponse> COES.MVC.Extranet.srGestor.ICMSManager.GetDataByUUIDAsync(COES.MVC.Extranet.srGestor.GetDataByUUIDRequest request) {
            return base.Channel.GetDataByUUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetDataByUUIDResponse> GetDataByUUIDAsync(string id) {
            COES.MVC.Extranet.srGestor.GetDataByUUIDRequest inValue = new COES.MVC.Extranet.srGestor.GetDataByUUIDRequest();
            inValue.id = id;
            return ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetDataByUUIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.srGestor.GetDataByPathResponse COES.MVC.Extranet.srGestor.ICMSManager.GetDataByPath(COES.MVC.Extranet.srGestor.GetDataByPathRequest request) {
            return base.Channel.GetDataByPath(request);
        }
        
        public System.Data.DataTable GetDataByPath(string id) {
            COES.MVC.Extranet.srGestor.GetDataByPathRequest inValue = new COES.MVC.Extranet.srGestor.GetDataByPathRequest();
            inValue.id = id;
            COES.MVC.Extranet.srGestor.GetDataByPathResponse retVal = ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetDataByPath(inValue);
            return retVal.GetDataByPathResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetDataByPathResponse> COES.MVC.Extranet.srGestor.ICMSManager.GetDataByPathAsync(COES.MVC.Extranet.srGestor.GetDataByPathRequest request) {
            return base.Channel.GetDataByPathAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetDataByPathResponse> GetDataByPathAsync(string id) {
            COES.MVC.Extranet.srGestor.GetDataByPathRequest inValue = new COES.MVC.Extranet.srGestor.GetDataByPathRequest();
            inValue.id = id;
            return ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetDataByPathAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.srGestor.GetDataByPathWithTypeResponse COES.MVC.Extranet.srGestor.ICMSManager.GetDataByPathWithType(COES.MVC.Extranet.srGestor.GetDataByPathWithTypeRequest request) {
            return base.Channel.GetDataByPathWithType(request);
        }
        
        public System.Data.DataTable GetDataByPathWithType(string path) {
            COES.MVC.Extranet.srGestor.GetDataByPathWithTypeRequest inValue = new COES.MVC.Extranet.srGestor.GetDataByPathWithTypeRequest();
            inValue.path = path;
            COES.MVC.Extranet.srGestor.GetDataByPathWithTypeResponse retVal = ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetDataByPathWithType(inValue);
            return retVal.GetDataByPathWithTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetDataByPathWithTypeResponse> COES.MVC.Extranet.srGestor.ICMSManager.GetDataByPathWithTypeAsync(COES.MVC.Extranet.srGestor.GetDataByPathWithTypeRequest request) {
            return base.Channel.GetDataByPathWithTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetDataByPathWithTypeResponse> GetDataByPathWithTypeAsync(string path) {
            COES.MVC.Extranet.srGestor.GetDataByPathWithTypeRequest inValue = new COES.MVC.Extranet.srGestor.GetDataByPathWithTypeRequest();
            inValue.path = path;
            return ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetDataByPathWithTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.srGestor.GetDataWithMetadataByPathResponse COES.MVC.Extranet.srGestor.ICMSManager.GetDataWithMetadataByPath(COES.MVC.Extranet.srGestor.GetDataWithMetadataByPathRequest request) {
            return base.Channel.GetDataWithMetadataByPath(request);
        }
        
        public System.Data.DataTable GetDataWithMetadataByPath(string path, string typeMetadata) {
            COES.MVC.Extranet.srGestor.GetDataWithMetadataByPathRequest inValue = new COES.MVC.Extranet.srGestor.GetDataWithMetadataByPathRequest();
            inValue.path = path;
            inValue.typeMetadata = typeMetadata;
            COES.MVC.Extranet.srGestor.GetDataWithMetadataByPathResponse retVal = ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetDataWithMetadataByPath(inValue);
            return retVal.GetDataWithMetadataByPathResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetDataWithMetadataByPathResponse> COES.MVC.Extranet.srGestor.ICMSManager.GetDataWithMetadataByPathAsync(COES.MVC.Extranet.srGestor.GetDataWithMetadataByPathRequest request) {
            return base.Channel.GetDataWithMetadataByPathAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetDataWithMetadataByPathResponse> GetDataWithMetadataByPathAsync(string path, string typeMetadata) {
            COES.MVC.Extranet.srGestor.GetDataWithMetadataByPathRequest inValue = new COES.MVC.Extranet.srGestor.GetDataWithMetadataByPathRequest();
            inValue.path = path;
            inValue.typeMetadata = typeMetadata;
            return ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetDataWithMetadataByPathAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.srGestor.GetDataAsJsonResponse COES.MVC.Extranet.srGestor.ICMSManager.GetDataAsJson(COES.MVC.Extranet.srGestor.GetDataAsJsonRequest request) {
            return base.Channel.GetDataAsJson(request);
        }
        
        public COES.MVC.Extranet.srGestor.Espacio[] GetDataAsJson(string luceneQuery, int pageSize, int start) {
            COES.MVC.Extranet.srGestor.GetDataAsJsonRequest inValue = new COES.MVC.Extranet.srGestor.GetDataAsJsonRequest();
            inValue.luceneQuery = luceneQuery;
            inValue.pageSize = pageSize;
            inValue.start = start;
            COES.MVC.Extranet.srGestor.GetDataAsJsonResponse retVal = ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetDataAsJson(inValue);
            return retVal.GetDataAsJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetDataAsJsonResponse> COES.MVC.Extranet.srGestor.ICMSManager.GetDataAsJsonAsync(COES.MVC.Extranet.srGestor.GetDataAsJsonRequest request) {
            return base.Channel.GetDataAsJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetDataAsJsonResponse> GetDataAsJsonAsync(string luceneQuery, int pageSize, int start) {
            COES.MVC.Extranet.srGestor.GetDataAsJsonRequest inValue = new COES.MVC.Extranet.srGestor.GetDataAsJsonRequest();
            inValue.luceneQuery = luceneQuery;
            inValue.pageSize = pageSize;
            inValue.start = start;
            return ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetDataAsJsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.srGestor.GetTotalNodesResponse COES.MVC.Extranet.srGestor.ICMSManager.GetTotalNodes(COES.MVC.Extranet.srGestor.GetTotalNodesRequest request) {
            return base.Channel.GetTotalNodes(request);
        }
        
        public int GetTotalNodes(string luceneQuery) {
            COES.MVC.Extranet.srGestor.GetTotalNodesRequest inValue = new COES.MVC.Extranet.srGestor.GetTotalNodesRequest();
            inValue.luceneQuery = luceneQuery;
            COES.MVC.Extranet.srGestor.GetTotalNodesResponse retVal = ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetTotalNodes(inValue);
            return retVal.GetTotalNodesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetTotalNodesResponse> COES.MVC.Extranet.srGestor.ICMSManager.GetTotalNodesAsync(COES.MVC.Extranet.srGestor.GetTotalNodesRequest request) {
            return base.Channel.GetTotalNodesAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetTotalNodesResponse> GetTotalNodesAsync(string luceneQuery) {
            COES.MVC.Extranet.srGestor.GetTotalNodesRequest inValue = new COES.MVC.Extranet.srGestor.GetTotalNodesRequest();
            inValue.luceneQuery = luceneQuery;
            return ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetTotalNodesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.srGestor.GetTotalNodesWithTypeResponse COES.MVC.Extranet.srGestor.ICMSManager.GetTotalNodesWithType(COES.MVC.Extranet.srGestor.GetTotalNodesWithTypeRequest request) {
            return base.Channel.GetTotalNodesWithType(request);
        }
        
        public int GetTotalNodesWithType(string path, string type) {
            COES.MVC.Extranet.srGestor.GetTotalNodesWithTypeRequest inValue = new COES.MVC.Extranet.srGestor.GetTotalNodesWithTypeRequest();
            inValue.path = path;
            inValue.type = type;
            COES.MVC.Extranet.srGestor.GetTotalNodesWithTypeResponse retVal = ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetTotalNodesWithType(inValue);
            return retVal.GetTotalNodesWithTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetTotalNodesWithTypeResponse> COES.MVC.Extranet.srGestor.ICMSManager.GetTotalNodesWithTypeAsync(COES.MVC.Extranet.srGestor.GetTotalNodesWithTypeRequest request) {
            return base.Channel.GetTotalNodesWithTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetTotalNodesWithTypeResponse> GetTotalNodesWithTypeAsync(string path, string type) {
            COES.MVC.Extranet.srGestor.GetTotalNodesWithTypeRequest inValue = new COES.MVC.Extranet.srGestor.GetTotalNodesWithTypeRequest();
            inValue.path = path;
            inValue.type = type;
            return ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetTotalNodesWithTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.srGestor.GetNormasLegalesResponse COES.MVC.Extranet.srGestor.ICMSManager.GetNormasLegales(COES.MVC.Extranet.srGestor.GetNormasLegalesRequest request) {
            return base.Channel.GetNormasLegales(request);
        }
        
        public System.Data.DataTable GetNormasLegales(string path, string type) {
            COES.MVC.Extranet.srGestor.GetNormasLegalesRequest inValue = new COES.MVC.Extranet.srGestor.GetNormasLegalesRequest();
            inValue.path = path;
            inValue.type = type;
            COES.MVC.Extranet.srGestor.GetNormasLegalesResponse retVal = ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetNormasLegales(inValue);
            return retVal.GetNormasLegalesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetNormasLegalesResponse> COES.MVC.Extranet.srGestor.ICMSManager.GetNormasLegalesAsync(COES.MVC.Extranet.srGestor.GetNormasLegalesRequest request) {
            return base.Channel.GetNormasLegalesAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetNormasLegalesResponse> GetNormasLegalesAsync(string path, string type) {
            COES.MVC.Extranet.srGestor.GetNormasLegalesRequest inValue = new COES.MVC.Extranet.srGestor.GetNormasLegalesRequest();
            inValue.path = path;
            inValue.type = type;
            return ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetNormasLegalesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.srGestor.GetFileIdByNameResponse COES.MVC.Extranet.srGestor.ICMSManager.GetFileIdByName(COES.MVC.Extranet.srGestor.GetFileIdByNameRequest request) {
            return base.Channel.GetFileIdByName(request);
        }
        
        public string GetFileIdByName(string name) {
            COES.MVC.Extranet.srGestor.GetFileIdByNameRequest inValue = new COES.MVC.Extranet.srGestor.GetFileIdByNameRequest();
            inValue.name = name;
            COES.MVC.Extranet.srGestor.GetFileIdByNameResponse retVal = ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetFileIdByName(inValue);
            return retVal.GetFileIdByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetFileIdByNameResponse> COES.MVC.Extranet.srGestor.ICMSManager.GetFileIdByNameAsync(COES.MVC.Extranet.srGestor.GetFileIdByNameRequest request) {
            return base.Channel.GetFileIdByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.srGestor.GetFileIdByNameResponse> GetFileIdByNameAsync(string name) {
            COES.MVC.Extranet.srGestor.GetFileIdByNameRequest inValue = new COES.MVC.Extranet.srGestor.GetFileIdByNameRequest();
            inValue.name = name;
            return ((COES.MVC.Extranet.srGestor.ICMSManager)(this)).GetFileIdByNameAsync(inValue);
        }
    }
}
